import type { 甲骨, Cel, Fn } from "../types/index.js";
import { bindNativeFns } from "./nativeFn.js";
import { compileInfix } from "./sheet/infix.js";
import { commitCell, cancelEdit, moveSelection, startEdit } from "./sheet/build.js";
import seed from "./sheet.json" with { type: "json" };

// ============================================================================
// sheet — the spreadsheet machinery segment: the `infix` FormulaCel parser
// and the four action cels. The per-sheet data layer (the N×M grid + control
// cels) is generated by buildSheet (re-exported below) and hydrated by the
// host. See docs/3-test-design/05-runCycle/spreadsheet-segment.md.
// ============================================================================

const infix: Fn = compileInfix as unknown as Fn;
infix.extractDeps = compileInfix.extractDeps;

export const name = "sheet" as const;

export const cels: Cel[] = bindNativeFns(seed as unknown as 甲骨, new Map<string, Fn>([
  ["infix",                infix],
  ["sheet.commit-cell",    commitCell],
  ["sheet.cancel-edit",    cancelEdit],
  ["sheet.move-selection", moveSelection],
  ["sheet.start-edit",     startEdit],
]));

export { buildSheet } from "./sheet/build.js";
export type { BuildSheetOpts } from "./sheet/build.js";
