// ============================================================================
// bundle — produce a single self-contained dist/index.html.
//
//   bun run bundle
//
// Bun's HTML-entrypoint bundler does the heavy lifting (bundles
// browser-main.ts + the kernel reachable from it, target=browser,
// minified). inline-assets.ts then folds every emitted sidecar back
// into the HTML so the deliverable is ONE file that runs off `file://`.
//
// The heavy, dynamic-imported kind runtimes are marked `external`:
// the kernel statically imports the wat / py / quickjs compiler SEGMENTS
// (small), but each only `import()`s its runtime (wabt ~1 MB, Pyodide
// ~10 MB, quickjs-emscripten) on first compile of that kind. The
// formula-domain demo never triggers them, so leaving the import()s
// external keeps them out of the static bundle without breaking the
// build. node:* specifiers (file-store's node-fs backend) are external
// for the same reason — the browser selects the OPFS backend.
// ============================================================================

import { join } from "node:path";
import { rm, readdir, readFile, writeFile } from "node:fs/promises";
import { inlineAssets } from "./inline-assets.js";

const OUT = join(import.meta.dir, "dist");
const HTML = join(OUT, "index.html");
// 20 MB budget — gzipped + base64'd doom.wasm + freedoom1.wad inflate the
// HTML to roughly 15 MB (WAD is the long pole at ~10 MB gzipped). The kernel
// + OS shell is well under 1 MB; the rest is Doom assets, decoded once and
// seeded into OPFS so subsequent boots skip the decode entirely.
const BUDGET = 20 * 1024 * 1024;

await rm(OUT, { recursive: true, force: true });

// ── Pre-bundle: inline doom.wasm + freedoom1.wad (gzipped, base64) ─────────
// The OS's Doom app reads these at runtime. For a single-file
// deliverable (open-anywhere, github-pages-friendly), inline both into a
// generated TS file the bundler picks up. The runtime checks OPFS first
// (seeded after the first decode), falls back to decoding the embedded
// gzip + DecompressionStream, and finally to fetch (dev-server / serve.ts).
// If an asset isn't present at build time, emit an empty-string placeholder
// so the build still works — the runtime then needs the fetch fallback.
const DOOM_WASM = join(import.meta.dir, "..", "doom", "doom.wasm");
const DOOM_WAD  = join(import.meta.dir, "..", "doom", "freedoom1.wad");
const DOOM_INLINE = join(import.meta.dir, "doom-assets-inline.ts");

const inlineAsset = async (label: string, srcPath: string): Promise<{ name: string; b64: string }> => {
  try {
    const raw = await readFile(srcPath);
    const gz = Bun.gzipSync(raw);
    const b64 = Buffer.from(gz).toString("base64");
    console.log(`✔ inlined ${label}: ${(raw.length / 1024).toFixed(0)} KB raw → ${(gz.length / 1024).toFixed(0)} KB gz → ${(b64.length / 1024).toFixed(0)} KB base64`);
    return { name: label, b64 };
  } catch {
    console.log(`  (skipped ${label} — file not at ${srcPath}; runtime falls back to fetch)`);
    return { name: label, b64: "" };
  }
};

const wasmAsset = await inlineAsset("doom.wasm", DOOM_WASM);
const wadAsset  = await inlineAsset("freedoom1.wad", DOOM_WAD);
await writeFile(
  DOOM_INLINE,
  `// Generated by bundle.ts. Do not commit; rerun \`bun run bundle\` to refresh.\n` +
  `// Strings are gzip-compressed bytes, base64-encoded. Decode at runtime via:\n` +
  `//   atob → Uint8Array → Blob → DecompressionStream("gzip") → bytes.\n` +
  `export const DOOM_WASM_GZ_B64 = "${wasmAsset.b64}";\n` +
  `export const DOOM_WAD_GZ_B64 = "${wadAsset.b64}";\n`,
);
// Clean up the old single-asset file if it's still lying around.
try { await rm(join(import.meta.dir, "doom-wasm-inline.ts"), { force: true }); } catch { /* not there */ }

const result = await Bun.build({
  entrypoints: [join(import.meta.dir, "index.html")],
  outdir: OUT,
  target: "browser",
  minify: true,
  sourcemap: "none",
  external: ["pyodide", "quickjs-emscripten", "wabt", "node:fs/promises", "node:path"],
});

if (!result.success) {
  for (const log of result.logs) console.error(log);
  throw new Error("bundle: Bun.build failed");
}

await inlineAssets(HTML);

const bytes = (await Bun.file(HTML).bytes()).length;
const leftovers = (await readdir(OUT)).filter((f) => f !== "index.html");

console.log(`✔ dist/index.html — ${(bytes / 1024).toFixed(1)} KB`);
if (leftovers.length) {
  throw new Error(`bundle: expected a single file, found extra: ${leftovers.join(", ")}`);
}
if (bytes > BUDGET) {
  throw new Error(`bundle: ${(bytes / 1024 / 1024).toFixed(2)} MB exceeds the 5 MB budget`);
}
